#!/usr/bin/env python3
"""Build every page of the site from the sources in _src/.

Why this exists: the nav, the <head> boilerplate, the footer and the dark-mode
script used to be copy-pasted into six files, so any change to one of them had
to be repeated six times. Here they live once, in _src/_partials/, and each page
pulls them in.

A source file starts with a front-matter comment and then the page body:

    <!--@
    out: blog/control-server-ros2.html
    active: blog
    base: ../
    i18n: yes
    title.ko: ...
    title.en: ...
    desc.ko: ...
    desc.en: ...
    head: <script src="..."></script>
    -->
    ...body...

Available in both partials and page bodies:

    {{> name}}    insert _src/_partials/<name>.html
    {{BASE}}      path prefix back to the site root ("" or "../")
    {{TITLE}}     page title for the language being built
    {{DESC}}      meta description for the language being built
    {{LANG}}      "ko" or "en"
    {{NAV_*}}     ' class="active"' on the matching nav item, else empty
    {{ALTLINKS}}  rel=alternate hreflang tags (bilingual pages only)
    {{SWITCH}}    the KR/EN nav link (bilingual pages only)
    {{EXTRAHEAD}} whatever the `head:` key holds

Bilingual pages additionally mark language-specific lines:

    <!--:ko--> ... <!--:/ko-->
    <!--:en--> ... <!--:/en-->

Everything outside those markers - code blocks, diagrams, scripts - is shared,
so it cannot drift between the two languages.

Usage:
    python3 tools/build.py           write every page
    python3 tools/build.py --check   report stale output without writing
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_src")
PARTIALS = os.path.join(SRC, "_partials")
SITE = "https://kwk2696.github.io"

LANGS = ("ko", "en")
LABEL = {"ko": "KR", "en": "EN"}
NAV_ITEMS = ("home", "publications", "demos", "blog")

FRONT_RE = re.compile(r"\A<!--@\s*\n(.*?)^-->\s*\n", re.S | re.M)
OPEN_RE = re.compile(r"<!--:(ko|en)-->\s*\Z")
CLOSE_RE = re.compile(r"<!--:/(ko|en)-->\s*\Z")
INCLUDE_RE = re.compile(r"\{\{>\s*([\w-]+)\s*\}\}")

BANNER = "<!-- Generated by tools/build.py from _src/%s. Edit that file. -->"


def die(msg):
    raise SystemExit("build: " + msg)


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def front_matter(text, path):
    m = FRONT_RE.match(text)
    if not m:
        die("%s has no <!--@ ... --> front matter" % path)
    meta = {}
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            die("%s: cannot parse front-matter line %r" % (path, line))
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()
    return meta, text[m.end():]


def split_langs(body, path):
    """Return [(text, lang_or_None)] segments, raising on unbalanced markers."""
    segments, current, buf = [], None, []
    for no, line in enumerate(body.splitlines(keepends=True), 1):
        stripped = line.strip()
        m = OPEN_RE.match(stripped)
        if m:
            if current:
                die("%s:%d: <!--:%s--> inside <!--:%s-->" % (path, no, m.group(1), current))
            segments.append(("".join(buf), None))
            buf, current = [], m.group(1)
            continue
        m = CLOSE_RE.match(stripped)
        if m:
            if current != m.group(1):
                die("%s:%d: unexpected <!--:/%s-->" % (path, no, m.group(1)))
            segments.append(("".join(buf), current))
            buf, current = [], None
            continue
        buf.append(line)
    if current:
        die("%s: <!--:%s--> was never closed" % (path, current))
    segments.append(("".join(buf), None))
    return segments


def out_name(out, lang):
    return out if lang == "ko" else re.sub(r"\.html\Z", ".%s.html" % lang, out)


def expand_includes(text, seen=()):
    def repl(m):
        name = m.group(1)
        if name in seen:
            die("partial %r includes itself" % name)
        path = os.path.join(PARTIALS, name + ".html")
        if not os.path.exists(path):
            die("no such partial: _src/_partials/%s.html" % name)
        return expand_includes(read(path).rstrip("\n"), seen + (name,))
    return INCLUDE_RE.sub(repl, text)


def render(meta, segments, lang, src_name):
    bilingual = meta.get("i18n", "no").lower() in ("yes", "true", "1")
    body = "".join(t for t, tag in segments if tag in (None, lang))
    page = expand_includes(body)

    out = meta["out"]
    if bilingual:
        alts = ['      <link rel="alternate" hreflang="%s" href="%s/%s">'
                % (other, SITE, out_name(out, other)) for other in LANGS]
        alts.append('      <link rel="alternate" hreflang="x-default" href="%s/%s">'
                    % (SITE, out))
        other = "en" if lang == "ko" else "ko"
        target = os.path.basename(out_name(out, other))
        switch = ('<a class="lang-switch" href="%s" hreflang="%s">%s</a>'
                  % (target, other, LABEL[other]))
    else:
        alts, switch = [], ""

    values = {
        "BASE": meta.get("base", ""),
        "LANG": lang if bilingual else meta.get("lang", "en"),
        "TITLE": meta.get("title.%s" % lang) or meta.get("title", ""),
        "DESC": meta.get("desc.%s" % lang) or meta.get("desc", ""),
        "ALTLINKS": "\n".join(alts),
        "SWITCH": switch,
        "EXTRAHEAD": meta.get("head", ""),
    }
    for item in NAV_ITEMS:
        values["NAV_" + item.upper()] = (
            ' class="active"' if meta.get("active") == item else "")

    for key, value in values.items():
        page = page.replace("{{%s}}" % key, value)
    # placeholders that render empty leave behind a blank line; drop those
    page = re.sub(r"\n[ \t]*\n(?=[ \t]*<(?:link|script|meta|button))", "\n", page)

    left = re.search(r"\{\{[A-Z_>][^}]*\}\}", page)
    if left:
        die("%s: unreplaced placeholder %s" % (src_name, left.group(0)))
    return page.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER % src_name, 1)


def sources():
    for base, _dirs, files in os.walk(SRC):
        if os.path.basename(base) == "_partials":
            continue
        for name in sorted(files):
            if name.endswith(".html"):
                yield os.path.join(base, name)


def main():
    check = "--check" in sys.argv
    if not os.path.isdir(SRC):
        die("no _src directory")

    problems, written = [], []
    for path in sorted(sources()):
        rel = os.path.relpath(path, SRC)
        meta, body = front_matter(read(path), rel)
        if "out" not in meta:
            die("%s: front matter needs an `out:` key" % rel)
        segments = split_langs(body, rel)

        bilingual = meta.get("i18n", "no").lower() in ("yes", "true", "1")
        if bilingual:
            n = {lang: sum(1 for _, tag in segments if tag == lang) for lang in LANGS}
            if n["ko"] != n["en"]:
                problems.append("%s: %d Korean blocks vs %d English blocks"
                                % (rel, n["ko"], n["en"]))
            targets = [(lang, out_name(meta["out"], lang)) for lang in LANGS]
        else:
            targets = [(meta.get("lang", "en"), meta["out"])]

        for lang, out in targets:
            text = render(meta, segments, lang, rel)
            dest = os.path.join(ROOT, out)
            if check:
                old = read(dest) if os.path.exists(dest) else ""
                if old != text:
                    problems.append("%s is out of date" % out)
            else:
                os.makedirs(os.path.dirname(dest) or ROOT, exist_ok=True)
                with open(dest, "w", encoding="utf-8") as fh:
                    fh.write(text)
                written.append(out)

    for p in problems:
        print("drift:", p)
    for w in written:
        print("wrote", w)
    if problems:
        return 1
    if check:
        print("in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
